# Copyright (c) 2023, NVIDIA CORPORATION.

# MIT License
#
# Modifications Copyright (C) 2025-2026 Advanced Micro Devices, Inc. All rights reserved.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

repos:
  - repo: local
    hooks:
          - id: check-license-installation
            name: check-license-installation
            entry: bash -c "type license_verificator >/dev/null 2>&1 || echo \"[WARNING] license verificator not installed!\" || true"
            language: system
            verbose: true
            pass_filenames: false
          - id: amd-copyright
            name: amd-copyright
            entry: bash -c "(! type license_verificator >/dev/null 2>&1) || license_verificator --pre-commit"
            language: system
            pass_filenames: false
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        exclude: |
          (?x)^(
            ^rapids-cmake/cpm/patches/.*
          )
      - id: end-of-file-fixer
        exclude: |
          (?x)^(
            ^rapids-cmake/cpm/patches/.*
          )
      - id: check-json
      - id: pretty-format-json
        args: ["--autofix", "--no-sort-keys"]
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v20.1.4
    hooks:
      - id: clang-format
        types_or: [c, c++, cuda]
        args: ["-fallback-style=none", "-style=file", "-i"]
  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        additional_dependencies: [tomli]
        args: ["--toml", "pyproject.toml"]
        exclude: |
          (?x)^(
            ^rapids-cmake/cpm/patches/.*
          )
  - repo: https://github.com/rapidsai/dependency-file-generator
    rev: v1.20.0
    hooks:
        - id: rapids-dependency-file-generator
          args: ["--clean", "--warn-all", "--strict"]
  - repo: local
    hooks:
      - id: cmake-format
        name: cmake-format
        entry: ./ci/checks/run-cmake-format.sh cmake-format
        language: python
        types: [cmake]
        # Note that pre-commit autoupdate does not update the versions
        # of dependencies, so we'll have to update this manually.
        additional_dependencies:
          - cmakelang==0.6.13
        verbose: true
        require_serial: true
      - id: cmake-lint
        name: cmake-lint
        entry: ./ci/checks/run-cmake-format.sh cmake-lint
        language: python
        types: [cmake]
        # Note that pre-commit autoupdate does not update the versions
        # of dependencies, so we'll have to update this manually.
        additional_dependencies:
          - cmakelang==0.6.13
        verbose: true
        require_serial: true
        exclude: |
          (?x)^(
            ^testing/.*$
          )
  - repo: https://github.com/rapidsai/pre-commit-hooks
    rev: v0.6.0
    hooks:
      - id: verify-copyright
        files: |
          (?x)
              [.](cmake|cpp|cu|cuh|h|hpp|sh|pxd|py|pyx)$|
              CMakeLists[.]txt$|
              meta[.]yaml$
      - id: verify-codeowners
        args: [--fix, --project-prefix=rapids, --no-cpp, --no-python]
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck

default_language_version:
  python: python3
